### ISSUE TITLE
Update to the latest lets-encrypt version: v0.4.0

### ISSUE THREAD

**Issue by Kriechi** [danzilio/puppet-letsencrypt#14]
Is there a reason or incompatibility why the version currently defaults to `v0.1.0` [here](https://github.com/danzilio/puppet-letsencrypt/blob/9bcf3c660dd9c69e7fcabbbb95fec74637fa70bd/manifests/params.pp#L11)?
lets-encrypt released `v0.4.0` a couple of days ago, and I think I would be nice to upgrade the default.

And with this new release there is now support for a `renew` command, which could be used in the cron job.
https://letsencrypt.readthedocs.org/en/latest/using.html#renewal

**Comment by danzilio** [comment]
No deliberate reason for this. PRs are welcome ;)

**Comment by danzilio** [comment]
Closed via #15
