### ISSUE TITLE
Invalid resource type ini_setting

### ISSUE THREAD

**Issue by fpieters** [danzilio/puppet-letsencrypt#22]
The whole error: 

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type ini_setting at /etc/puppet/environments/production/modules/letsencrypt/manifests/config/ini.pp:21

**Puppet version: 3.8.4
OS: Ubuntu 14.04.3 LTS**

Its fixed by using the [inifile module](https://github.com/puppetlabs/puppetlabs-inifile) from pupppetlabs

**Comment by danzilio** [comment]
hey @fpieters! inifile is listed as a dependency in the module's metadata (see: https://github.com/danzilio/puppet-letsencrypt/blob/master/metadata.json#L55-L56). did the dependency not install when you installed the module? how did you install the module?

**Comment by fpieters** [comment]
Ah then its my mistake. I just did a simple clone.
