### ISSUE TITLE
Command Questions

### ISSUE THREAD

**Issue by lazyfrosch** [danzilio/puppet-letsencrypt#26]
During implementation yesterday I came up to a few "problems":

* The cron outputs senseless info every time:
```
Checking for new version...
Requesting root privileges to run letsencrypt...
   /opt/letsencrypt/.venv/bin/letsencrypt --agree-tos certonly -a webroot --keep-until-expiring --webroot-path /var/www/html -d test.example.com
```
* Should we use `--no-self-upgrade` on cron and certonly?
* Should we use `/opt/letsencrypt/.venv/bin/letsencrypt`, and call letsencrypt-auto only once?

**Comment by danzilio** [comment]
@lazyfrosch merged your PR for this. Thanks!
