### ISSUE TITLE
Duplicate declaration: Package[git] is already declared in file 

### ISSUE THREAD

**Issue by jg-development** [danzilio/puppet-letsencrypt#29]
Hi,
I manage git with another module. This results in a duplicate declaration error.
I might be better to handle the packages with the
"ensure_resource('package', $packages, {'ensure' => 'present'})"
from the stdlib module.

Thanks in advance
Jan

**Comment by danzilio** [comment]
Hi @jg-development, we already use `ensure_packages` for this but the `ensure_*` functions are still parse-order dependent. I would recommend setting `manage_dependencies` to `false` for your case.
