### ISSUE TITLE
undefined method `cycle' 

### ISSUE THREAD

**Issue by seefood** [danzilio/puppet-letsencrypt#37]
`Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse inline template: undefined method `cycle' for nil:NilClass at /etc/puppetlabs/code/environments/production/modules/letsencrypt/manifests/certonly.pp:47:18`

CentOS7
`# /opt/puppetlabs/puppet/bin/ruby --version
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]`

what am I missing?

**Comment by domcleal** [comment]
I think you're probably missing the `webroot_paths` parameter to letsencrypt::certonly, which should be an array of paths of your webroot(s) when using the webroot plugin.

**Comment by seefood** [comment]
true. I was naiively assuming there would be a fallback default, just didn't go looking for it :)
Worth a README example code, maybe?

**Comment by danzilio** [comment]
We can add some validation logic to ensure that `webroot_paths` isn't `undef` when the plugin is set to `webroot`

**Comment by seefood** [comment]
I thought maybe it could fall back to "/var/www/html" os something sensible like that...

**Comment by domcleal** [comment]
I don't think there's a good cross-server and cross-OS default for the parameter, so requiring it is probably safest to prevent stranger errors when trying to request certificates.
