### ISSUE TITLE
1.0.0 and 0.4.0 packages in puppetforge broken

### ISSUE THREAD

**Issue by sHaggYcaT** [danzilio/puppet-letsencrypt#46]
1.0.0 package in puppetforge broken:

```
These files existed in the module's tar file, but are invalid filetypes and were not unpacked: ["PaxHeader/danzilio-letsencrypt-1.0.0", "danzilio-letsencrypt-1.0.0/PaxHeader/CHANGELOG.md", "danzilio-letsencrypt-1.0.0/PaxHeader/checksums.json", "danzilio-letsencrypt-1.0.0/PaxHeader/Gemfile", "danzilio-letsencrypt-1.0.0/PaxHeader/LICENSE", "danzilio-letsencrypt-1.0.0/PaxHeader/manifests", "danzilio-letsencrypt-1.0.0/PaxHeader/metadata.json", "danzilio-letsencrypt-1.0.0/PaxHeader/Rakefile", "danzilio-letsencrypt-1.0.0/PaxHeader/README.md", "danzilio-letsencrypt-1.0.0/PaxHeader/spec", "danzilio-letsencrypt-1.0.0/spec/PaxHeader/classes", "danzilio-letsencrypt-1.0.0/spec/PaxHeader/defines", "danzilio-letsencrypt-1.0.0/spec/PaxHeader/spec_helper.rb", "danzilio-letsencrypt-1.0.0/spec/defines/PaxHeader/letsencrypt_certonly_spec.rb", "danzilio-letsencrypt-1.0.0/spec/classes/PaxHeader/letsencrypt_install_spec.rb", "danzilio-letsencrypt-1.0.0/spec/classes/PaxHeader/letsencrypt_spec.rb", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/certonly.pp", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/config", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/config.pp", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/init.pp", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/install.pp", "danzilio-letsencrypt-1.0.0/manifests/PaxHeader/params.pp", "danzilio-letsencrypt-1.0.0/manifests/config/PaxHeader/ini.pp"]
remote: ERROR    -> undefined method `full_module_name' for nil:NilClass

```

Code of package 0.4.0 broken too:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'Optional'; expected ')' at /etc/puppet/environments/*/modules/letsencrypt/manifests/init.pp:31 on node dev3.*.site
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by domcleal** [comment]
> Code of package 0.4.0 broken too:

This release was only compatible with Puppet 4.0 or higher. You need version 1.0.0 or higher to use Puppet 3.4 - 3.8, or enable the future parser.

**Comment by sHaggYcaT** [comment]
Ah, ok. How about bug in 1.0.0 git tag?

**Comment by domcleal** [comment]
> These files existed in the module's tar file, but are invalid filetypes and were not unpacked: ["PaxHeader/danzilio-letsencrypt-1.0.0", ...

These are virtual files added by GNU tar, looks like you might be using r10k which warns about them. https://tickets.puppetlabs.com/browse/RK-238 appears to reduce the logging severity.

I don't know about the full_module_name error, but there are some tickets in r10k's tracker mentioning it - perhaps rule out if it's an issue in r10k or pointing to an issue in the module?

A basic `puppet module install` works fine and the metadata.json appears valid to me and metadata-json-lint.

**Comment by sHaggYcaT** [comment]
Thank you very much for your support.

Yes, you're right. In latest version of r10k (2.3.0) problem doesn't reproduce.
But I've got another problem,  

`letsencrypt: Please read the Terms of Service at https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf. You must agree in order to register with the ACME server at
`
May be it's not bug, or if it bug it required different ticket here. I've just send you email in your address in RedHat.com domain.
